### ISSUE TITLE
Issue adding new migration to project

### ISSUE THREAD

**Issue by nathanfisher** [vkhorikov/EFCoreEncapsulation#2]
More of a question than an issue since the course does not speak about adding migrations. I am getting the following error when trying to add a new migration script using the add-migration command. The verbose switch reveals this: 

Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'MyDBContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: Unable to resolve service for type 'System.String' while attempting to activate 'MyEFCoreProject.EntityFrameworkCore.MyDBContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_4.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_4.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

 Not quite sure what I am doing wrong. I also reverted the constructor and registration back to the original before your encapsulation modifications and also got an error message.

System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1 

Program.cs

//builder.Services.AddScoped(_ => new PaceFillsContext(builder.Configuration["ConnectionString"], true));

builder.Services.AddDbContext<PaceFillsContext>(options =>
    options.UseSqlServer(builder.Configuration["ConnectionString"]));

Before builder.Build() is called 

public MyDBContext(DbContextOptions<PaceFillsContext> options) : base(options)
    {
    }

    //public MyDBContext(string connectionString, bool useConsoleLogger)
    //{
    //    _connectionString = connectionString;
    //    _useConsoleLogger = useConsoleLogger;
    //}

**Comment by vkhorikov** [comment]
I haven't worked with EF Core migrations for a long time, so not sure what's going on here. I personally use either `FluentMigration` library or this simple one: https://github.com/vkhorikov/DatabaseUpgradeTool

**Comment by nathanfisher** [comment]
Thanks so much for the suggestion I will look into FluentMigrations more.
